version: '3'

services:
  api:
    build: api
    ports:
      - '80:80'
    depends_on:
      - db
      - postgres

  db:
    build: db
    ports:
      - '6379:6379'
    volumes:
      - .data:/data

  postgres:
    build: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      # - POSTGRES_PASSWORD=gorm
      # - POSTGRES_USER=gorm
      # - POSTGRES_DB=gorm
      # - POSTGRES_HOST=gorm

      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    volumes:
      - .database_data:/data
    ports:
      - 5432:5432
