version: '3'

services:
  api:
    build: api
    ports:
      - '80:80'
    depends_on:
      - db
      - postgres

  db:
    build: db
    ports:
      - '6379:6379'
    volumes:
      - .data:/data

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      # Optional: Give a name to the database, otherwise
      # use the default value POSTGRES_USER as a database name (user in this case.)
      # POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: # create the volume for persisting data.